name = "transvela"
compatibility_date = "2024-11-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "transvela-db"
database_id = "c7ccbd13-1907-4495-a4af-f5c0053513a2"
